(setq package-archives '(("gnu" . "http://elpa.gnu.org/packages/")
                         ("marmalade" . "http://marmalade-repo.org/packages/")
                         ("melpa" . "http://melpa.milkbox.net/packages/")))
(add-to-list 'load-path "~/.emacs.d/scripts")
(scroll-bar-mode -1)
(setq initial-scratch-buffer nil)
(require 'follow-mouse)
(turn-on-follow-mouse)
(package-initialize)
(require 'evil)
(evil-mode 1)
(require 'key-chord)
(setq key-chord-two-keys-delay 0.5)
(key-chord-define evil-insert-state-map "ii" 'evil-normal-state)
(key-chord-mode 1)
(set-default-font "InconsolataLGC-12")
(load-theme 'solarized-dark t)
(require 'frame-cmds)
(require 'nav)
(setq w (selected-window))
(setq w2 (split-window w -16))
(select-window w2)
(ansi-term "zsh")
(require 'load-theme-buffer-local)
(load-theme-buffer-local 'solarized-light t)
(select-window w)
(nav)
